# -*- coding: utf-8 -*-
"""New MCP Social Media.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DflMIxnpthulQpbLsx9TXipU-GD2TEwk

Imports + JSON Loading + DataFrame Setup
"""

import pandas as pd
import json
from datetime import datetime, timedelta
import random

# Load JSON file
with open("/content/nucleus.instagram_output_ps(1).json") as f:
    data = json.load(f)

# Convert to DataFrame
df = pd.DataFrame(data)

# Rename columns to match original logic
df.rename(columns={
    "post_owner_name": "profile",
    "post_content": "text"
}, inplace=True)

# Add dummy date column for testing date filters
base_date = datetime(2024, 1, 1)
df['date'] = [
    (base_date + timedelta(days=random.randint(0, 180))).strftime('%Y-%m-%d')
    for _ in range(len(df))
]

"""Query Function"""

def query_data(profile=None, keyword=None, start_date=None, end_date=None):
    results = df.copy()

    if profile:
        results = results[results['profile'].str.lower() == profile.lower()]

    if keyword:
        results = results[results['text'].str.contains(keyword, case=False)]

    if start_date:
        results = results[results['date'] >= start_date]

    if end_date:
        results = results[results['date'] <= end_date]

    return results.reset_index(drop=True)

""" Prompt Parsing (simulate_llm_query)"""

import re

def simulate_llm_query(prompt):
    prompt = prompt.lower()

    profile = None
    keyword = None
    start_date = None
    end_date = None

    # Profile detection (e.g., "posts by elonmusk")
    profile_match = re.search(r"posts by ([a-zA-Z0-9_.]+)", prompt)
    if profile_match:
        profile = profile_match.group(1)

    #  Keyword detection (e.g., "mentioning zakayo" or "about ruto")
    keyword_match = re.search(r"(mentioning|about)\s+'?\"?([a-zA-Z0-9#@.\s]+)'?\"?", prompt)
    if keyword_match:
        keyword = keyword_match.group(2).strip()

    # Zakayo-type keywords (simple detection)
    if "zakayo" in prompt and not keyword:
        keyword = "zakayo"

    if "bruce lee" in prompt and not keyword:
        keyword = "bruce lee"

    if "ruto" in prompt and not keyword:
        keyword = "ruto"

    if "finance bill" in prompt and not keyword:
        keyword = "finance bill"

    if "robot" in prompt and not keyword:
        keyword = "robot"

    # Date-range detection (if you added dummy date column)
    if "between jan 2024 and march 2024" in prompt:
        start_date = "2024-01-01"
        end_date = "2024-03-31"

    if profile or keyword or start_date or end_date:
        return query_data(profile=profile, keyword=keyword, start_date=start_date, end_date=end_date)

    # Default fallback
    return pd.DataFrame([{"error": "LLM could not interpret the query. Try another prompt."}])

"""Gradio Interface"""

import gradio as gr

def llm_query_interface(prompt):
    result = simulate_llm_query(prompt)
    return result

gr.Interface(
    fn=llm_query_interface,
    inputs=gr.Textbox(lines=2, placeholder="Ask like LLM: Show me posts by zubic_communication"),
    outputs=gr.Dataframe(),
    title="MCP Server - LLM Query Interface",
    description="Enter a natural language query. E.g. 'Show me posts by brucelee' or 'Find posts mentioning zakayo'"
).launch()